seed: 2027
label: v0333_no_logic
base_model_id: TinyLlama/TinyLlama-1.1B-Chat-v1.0
precision: bf16
lora_enable: true
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
batch_size: 8
train_steps: 200
warmup_steps: 20
lr: 2.0e-4
weight_decay: 0.01

router_balance_lambda: 3.0e-3
router_noise_std: 0.03
expert_dropout_p: 0.02
block_memdrop_prob: 0.0
cross_block_balance_lambda: 0.0

data:
  weight_policy: uniform
  sticky_mix: 10
  hf_max_items: 400
  tasks:
    # code
    - { name: mbpp, type: hf, dataset: mbpp, max_items: 400 }
    - { name: apps, type: hf, dataset: codeparrot/apps, max_items: 400 }
    # math
    - { name: gsm8k, type: hf, dataset: gsm8k, max_items: 400 }
    - { name: aqua, type: hf, dataset: aqua_rat, max_items: 400 }

    # algorithmic (synthetic)
    - { name: dyck, type: synth, kind: dyck, params: { depth: 3, T: 64 } }
    - { name: stack, type: synth, kind: stack_ops, params: { ops: 16 } }
    - { name: sort, type: synth, kind: sort_list, params: { length: 10, vocab: 50 } }
